export const mockStaff = [
  {
    name: "Aleksander Grande",
    position: "Utvikler og fagsjef",
    location: "grimstad",
    department: "design",
  },
  {
    name: "An Mai Lee",
    position: "Testleder",
    location: "oslo",
    department: "administration",
  },
  {
    name: "Anders Blehr",
    position: "Arkitekt",
    location: "oslo",
    department: "utvikling",
  },
  {
    name: "Anders Hefre",
    position: "Teamleder og avdelingsleder",
    location: "oslo",
    department: "arkitektur",
  },
  {
    name: "Andreas Berg",
    position: "Utvikler og AI Engineer",
    location: "hamar",
    department: "analyse",
  },
  {
    name: "Andreas Fuglesang",
    position: "Utvikler",
    location: "hamar",
    department: "design",
  },
  {
    name: "Ane Sæther",
    position: "Utvikler",
    location: "oslo",
    department: "test",
  },
  {
    name: "Ann-Sofie Jansson Ulle",
    position: "Utvikler",
    location: "oslo",
    department: "test",
  },
  {
    name: "Are Thobias Tysnes",
    position: "Testleder",
    location: "grimstad",
    department: "prosjektledelse",
  },
  {
    name: "Arne Jørgen Arnesen",
    position: "Utvikler",
    location: "hamar",
    department: "plattform",
  },
  {
    name: "Bendik Ivar Hasselknippe Tiltnes",
    position: "Utvikler",
    location: "grimstad",
    department: "prosjektledelse",
  },
  {
    name: "Bettine Deschington",
    position: "Leder strategisk salg og partnerskap",
    location: "hamar",
    department: "plattform",
  },
  {
    name: "Bjørn Sloth",
    position: "Produkteier/Agile coach",
    location: "grimstad",
    department: "plattform",
  },
  {
    name: "Bjørn Åge Tungesvik",
    position: "Plattformutvikler",
    location: "hamar",
    department: "utvikling",
  },
  {
    name: "Carina Kristensen",
    position: "Kontor og marked",
    location: "hamar",
    department: "test",
  },
  {
    name: "Carl Jørund Svensen",
    position: "Utvikler",
    location: "oslo",
    department: "plattform",
  },
  {
    name: "Carl Magnusson",
    position: "Plattformutvikler",
    location: "oslo",
    department: "utvikling",
  },
  {
    name: "Cecilie Haugstvedt",
    position: "Testleder",
    location: "hamar",
    department: "arkitektur",
  },
  {
    name: "Charlotte Irgens",
    position: "Leder salg og marked",
    location: "hamar",
    department: "utvikling",
  },
  {
    name: "Christian Aarthun",
    position: "Testutvikler",
    location: "grimstad",
    department: "test",
  },
  {
    name: "Cornelius Grieg Dahling",
    position: "Plattformutvikler",
    location: "hamar",
    department: "utvikling",
  },
  {
    name: "Dag W. Findal-Fossmo",
    position: "Arkitekt",
    location: "grimstad",
    department: "administration",
  },
  {
    name: "Daniel Eriksson",
    position: "Utvikler",
    location: "oslo",
    department: "plattform",
  },
  {
    name: "Daniel Tafjord",
    position: "Utvikler",
    location: "oslo",
    department: "analyse",
  },
  {
    name: "David Emanuelsen",
    position: "Utvikler",
    location: "grimstad",
    department: "analyse",
  },
  {
    name: "Diego Pasten",
    position: "Plattformutvikler",
    location: "grimstad",
    department: "test",
  },
  {
    name: "Embrik Tvenge Einang",
    position: "Utvikler",
    location: "oslo",
    department: "analyse",
  },
  {
    name: "Emil Ramsvik",
    position: "Data Engineer",
    location: "oslo",
    department: "test",
  },
  {
    name: "Erik Aaron Hansen",
    position: "Plattformutvikler",
    location: "grimstad",
    department: "administration",
  },
  {
    name: "Erlend Johansen",
    position: "Testutvikler",
    location: "oslo",
    department: "plattform",
  },
  {
    name: "Erling Johansen",
    position: "Utvikler",
    location: "grimstad",
    department: "prosjektledelse",
  },
  {
    name: "Espen Nygård",
    position: "Rådgiver og avdelingsleder",
    location: "grimstad",
    department: "utvikling",
  },
  {
    name: "Espen Warg Næss",
    position: "Utvikler",
    location: "grimstad",
    department: "test",
  },
  {
    name: "Fredrik Larsen",
    position: "Controller",
    location: "hamar",
    department: "design",
  },
  {
    name: "Gard Sæbø",
    position: "Utvikler",
    location: "hamar",
    department: "design",
  },
  {
    name: "Hager Debech",
    position: "Avdelingsleder",
    location: "hamar",
    department: "analyse",
  },
  {
    name: "Hans Børge Pedersen",
    position: "Utvikler",
    location: "hamar",
    department: "design",
  },
  {
    name: "Hans Fredrik Furholt",
    position: "Utvikler",
    location: "oslo",
    department: "arkitektur",
  },
  {
    name: "Hans Ole Gjerdrum",
    position: "Utvikler",
    location: "grimstad",
    department: "administration",
  },
  {
    name: "Harald Grønlie Nyhus",
    position: "Utvikler",
    location: "hamar",
    department: "analyse",
  },
  {
    name: "Harald Kuhr",
    position: "Utvikler",
    location: "hamar",
    department: "design",
  },
  {
    name: "Harald Skoglund",
    position: "Plattformutvikler",
    location: "hamar",
    department: "administration",
  },
  {
    name: "Haris Malik",
    position: "Utvikler",
    location: "grimstad",
    department: "prosjektledelse",
  },
  {
    name: "Helene Iversen",
    position: "UX-designer",
    location: "hamar",
    department: "administration",
  },
  {
    name: "Henning Engen",
    position: "Utvikler",
    location: "hamar",
    department: "utvikling",
  },
  {
    name: "Herman Jakobsen",
    position: "Utvikler",
    location: "oslo",
    department: "design",
  },
  {
    name: "Håkon Berg",
    position: "Utvikler",
    location: "grimstad",
    department: "arkitektur",
  },
  {
    name: "Håvard Lødemel",
    position: "Utvikler",
    location: "grimstad",
    department: "utvikling",
  },
  {
    name: "Håvard Neegård Bjurholt",
    position: "CTO",
    location: "oslo",
    department: "design",
  },
  {
    name: "Igor Radulovic",
    position: "Plattformutvikler",
    location: "grimstad",
    department: "analyse",
  },
  {
    name: "Inam Qadir",
    position: "Testleder",
    location: "oslo",
    department: "utvikling",
  },
  {
    name: "Ivo Ivanov",
    position: "Utvikler",
    location: "oslo",
    department: "design",
  },
  {
    name: "Jacob Meidell",
    position: "Utvikler",
    location: "oslo",
    department: "plattform",
  },
  {
    name: "Jacob Nilsen",
    position: "Utvikler",
    location: "hamar",
    department: "design",
  },
  {
    name: "Jakob Lade Stenvaag",
    position: "Utvikler",
    location: "hamar",
    department: "plattform",
  },
  {
    name: "Jan Henning Alstergren",
    position: "Utvikler",
    location: "oslo",
    department: "prosjektledelse",
  },
  {
    name: "Jan Sviland",
    position: "Utvikler",
    location: "oslo",
    department: "utvikling",
  },
  {
    name: "Jarle Hansen",
    position: "Utvikler",
    location: "oslo",
    department: "prosjektledelse",
  },
  {
    name: "Jo Dybdal",
    position: "Utvikler",
    location: "hamar",
    department: "prosjektledelse",
  },
  {
    name: "Joanne Cuffey",
    position: "Utvikler",
    location: "grimstad",
    department: "design",
  },
  {
    name: "Johan Magne Haugland",
    position: "Utvikler",
    location: "hamar",
    department: "administration",
  },
  {
    name: "Jostein Holje",
    position: "Utvikler",
    location: "oslo",
    department: "test",
  },
  {
    name: "Karl Jørgen Overå",
    position: "Utvikler",
    location: "oslo",
    department: "analyse",
  },
  {
    name: "Kicki Holmberg",
    position: "Rekrutterer og HR-rådgiver",
    location: "oslo",
    department: "plattform",
  },
  {
    name: "Kim Sverre Hilton",
    position: "Utvikler",
    location: "oslo",
    department: "administration",
  },
  {
    name: "Kine Øverby-Jahnsen",
    position: "Agile Coach",
    location: "oslo",
    department: "design",
  },
  {
    name: "Knut Nymoen",
    position: "Rådgiver",
    location: "grimstad",
    department: "administration",
  },
  {
    name: "Kristofer Koppang",
    position: "Rekrutteringsansvarlig",
    location: "oslo",
    department: "administration",
  },
  {
    name: "Lars Furuheim",
    position: "UX-designer",
    location: "hamar",
    department: "design",
  },
  {
    name: "Lars Marius Bjørneseth",
    position: "Utvikler",
    location: "oslo",
    department: "test",
  },
  {
    name: "Lars Myhrum",
    position: "Daglig leder",
    location: "hamar",
    department: "plattform",
  },
  {
    name: "Linda Katrine Andresen",
    position: "UX-designer",
    location: "grimstad",
    department: "utvikling",
  },
  {
    name: "Mads Karlstad",
    position: "Utvikler",
    location: "hamar",
    department: "prosjektledelse",
  },
  {
    name: "Magdalena Tran",
    position: "Utvikler",
    location: "hamar",
    department: "design",
  },
  {
    name: "Markus Medalen",
    position: "Utvikler",
    location: "hamar",
    department: "plattform",
  },
  {
    name: "Martin Almvik",
    position: "Utvikler",
    location: "hamar",
    department: "test",
  },
  {
    name: "Martin Gunnerud",
    position: "Utvikler",
    location: "hamar",
    department: "analyse",
  },
  {
    name: "Martin Laupet",
    position: "Utvikler",
    location: "grimstad",
    department: "plattform",
  },
  {
    name: "Mikael Rino Solstad",
    position: "Utvikler og avdelingsleder",
    location: "grimstad",
    department: "analyse",
  },
  {
    name: "Mikkel Næss",
    position: "Utvikler",
    location: "oslo",
    department: "analyse",
  },
  {
    name: "Mikkel Sannes Nylend",
    position: "Utvikler og AI Engineer",
    location: "oslo",
    department: "prosjektledelse",
  },
  {
    name: "Mirela Divic",
    position: "Agile Coach",
    location: "hamar",
    department: "utvikling",
  },
  {
    name: "Morten Punnerud Engelstad",
    position: "Data Engineer",
    location: "hamar",
    department: "administration",
  },
  {
    name: "Nathaniel Tadesse",
    position: "Plattformutvikler",
    location: "grimstad",
    department: "arkitektur",
  },
  {
    name: "Nicolina Knudtzon",
    position: "COO",
    location: "hamar",
    department: "design",
  },
  {
    name: "Nikolai Sverdrup",
    position: "Utvikler",
    location: "grimstad",
    department: "arkitektur",
  },
  {
    name: "Odd-Arne Bjørklund",
    position: "Testleder",
    location: "grimstad",
    department: "test",
  },
  {
    name: "Ole Myrbakken",
    position: "Utvikler og avdelingsleder",
    location: "oslo",
    department: "arkitektur",
  },
  {
    name: "Per-Bjørnar Iversen",
    position: "Testutvikler",
    location: "oslo",
    department: "prosjektledelse",
  },
  {
    name: "Petr Dreiseitl",
    position: "Testleder",
    location: "grimstad",
    department: "administration",
  },
  {
    name: "Richard Bertelsen",
    position: "Forretningsutvikler",
    location: "grimstad",
    department: "administration",
  },
  {
    name: "Rune Myklevoll",
    position: "Utvikler",
    location: "grimstad",
    department: "analyse",
  },
  {
    name: "Sebastian Dehne",
    position: "Arkitekt",
    location: "grimstad",
    department: "plattform",
  },
  {
    name: "Shomaila Kausar",
    position: "Testleder og avdelingsleder",
    location: "oslo",
    department: "prosjektledelse",
  },
  {
    name: "Simen Nordby Johansen",
    position: "Utvikler",
    location: "hamar",
    department: "design",
  },
  {
    name: "Simen Søhol",
    position: "Utvikler",
    location: "oslo",
    department: "prosjektledelse",
  },
  {
    name: "Siri Mykland",
    position: "Utvikler",
    location: "hamar",
    department: "utvikling",
  },
  {
    name: "Snorre Berge",
    position: "UX-designer",
    location: "oslo",
    department: "test",
  },
  {
    name: "Sverre Sveum Moen",
    position: "Data Engineer",
    location: "oslo",
    department: "administration",
  },
  {
    name: "Tage Veflingstad",
    position: "Utvikler",
    location: "hamar",
    department: "prosjektledelse",
  },
  {
    name: "Terje Karlsen",
    position: "Utvikler",
    location: "oslo",
    department: "arkitektur",
  },
  {
    name: "Therese Marie Hagen",
    position: "UX-designer",
    location: "hamar",
    department: "utvikling",
  },
  {
    name: "Thomas Aron Aasen",
    position: "Utvikler",
    location: "oslo",
    department: "utvikling",
  },
  {
    name: "Tommy Madsen",
    position: "UX-designer og avdelingsleder",
    location: "hamar",
    department: "analyse",
  },
  {
    name: "Tony Olsen",
    position: "Utvikler",
    location: "hamar",
    department: "utvikling",
  },
  {
    name: "Trond Hagehaugen",
    position: "Testleder",
    location: "grimstad",
    department: "prosjektledelse",
  },
  {
    name: "Vegard Nyeng",
    position: "Testutvikler",
    location: "hamar",
    department: "analyse",
  },
  {
    name: "Vijay Shanmugappirabu",
    position: "Arkitekt",
    location: "hamar",
    department: "plattform",
  },
  {
    name: "William Benjamin Wold",
    position: "Utvikler og Data Engineer",
    location: "oslo",
    department: "plattform",
  },
  {
    name: "Willy Miao",
    position: "Plattformutvikler",
    location: "oslo",
    department: "test",
  },
  {
    name: "Ævar Eggertsson",
    position: "Utvikler",
    location: "oslo",
    department: "administration",
  },
  {
    name: "Øystein Fossum",
    position: "Data Engineer",
    location: "grimstad",
    department: "prosjektledelse",
  },
  {
    name: "Øystein Jardar Songstad",
    position: "Utvikler",
    location: "grimstad",
    department: "prosjektledelse",
  },
  {
    name: "Øystein Rose",
    position: "Utvikler",
    location: "hamar",
    department: "utvikling",
  },
  {
    name: "Øyvind Dahl Syrstad",
    position: "Avdelingsleder og arkitekt",
    location: "grimstad",
    department: "test",
  },
  {
    name: "Øyvind Skytøen",
    position: "Utvikler",
    location: "oslo",
    department: "administration",
  },
  {
    name: "Åste Reppe",
    position: "Prosjektleder",
    location: "hamar",
    department: "prosjektledelse",
  },
];
