/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type Contact = {
  name: string;
  email: string;
  title: string;
  description: string;
  image: ContactImage;
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type ContactImage = {
  asset?: SanityImageAssetReference;
  media?: unknown; // Unable to locate the referenced type "media" in schema
  hotspot?: SanityImageHotspot;
  crop?: SanityImageCrop;
  alt: string;
  _type: "image";
};

export type First = {
  asset?: SanityImageAssetReference;
  media?: unknown; // Unable to locate the referenced type "first.media" in schema
  hotspot?: SanityImageHotspot;
  crop?: SanityImageCrop;
  alt?: string;
  _type: "image";
};

export type Second = {
  asset?: SanityImageAssetReference;
  media?: unknown; // Unable to locate the referenced type "second.media" in schema
  hotspot?: SanityImageHotspot;
  crop?: SanityImageCrop;
  alt?: string;
  _type: "image";
};

export type Third = {
  asset?: SanityImageAssetReference;
  media?: unknown; // Unable to locate the referenced type "third.media" in schema
  hotspot?: SanityImageHotspot;
  crop?: SanityImageCrop;
  alt?: string;
  _type: "image";
};

export type Fourth = {
  asset?: SanityImageAssetReference;
  media?: unknown; // Unable to locate the referenced type "fourth.media" in schema
  hotspot?: SanityImageHotspot;
  crop?: SanityImageCrop;
  alt?: string;
  _type: "image";
};

export type ImageTwoFirst = {
  asset?: SanityImageAssetReference;
  media?: unknown; // Unable to locate the referenced type "imageTwo.first.media" in schema
  hotspot?: SanityImageHotspot;
  crop?: SanityImageCrop;
  alt?: string;
  caption?: string;
  _type: "image";
};

export type ImageTwoSecond = {
  asset?: SanityImageAssetReference;
  media?: unknown; // Unable to locate the referenced type "imageTwo.second.media" in schema
  hotspot?: SanityImageHotspot;
  crop?: SanityImageCrop;
  alt?: string;
  caption?: string;
  _type: "image";
};

export type ImagesThreeFirst = {
  asset?: SanityImageAssetReference;
  media?: unknown; // Unable to locate the referenced type "imagesThree.first.media" in schema
  hotspot?: SanityImageHotspot;
  crop?: SanityImageCrop;
  alt?: string;
  _type: "image";
};

export type ImagesThreeSecond = {
  asset?: SanityImageAssetReference;
  media?: unknown; // Unable to locate the referenced type "imagesThree.second.media" in schema
  hotspot?: SanityImageHotspot;
  crop?: SanityImageCrop;
  alt?: string;
  _type: "image";
};

export type ImagesThreeThird = {
  asset?: SanityImageAssetReference;
  media?: unknown; // Unable to locate the referenced type "imagesThree.third.media" in schema
  hotspot?: SanityImageHotspot;
  crop?: SanityImageCrop;
  alt?: string;
  _type: "image";
};

export type ImageGallery = {
  first: First;
  second: Second;
  third: Third;
  fourth: Fourth;
};

export type WorkHere = {
  label: string;
  title: string;
  description: string;
  points?: Array<string>;
  image: WorkHereImage;
};

export type WorkHereImage = {
  asset?: SanityImageAssetReference;
  media?: unknown; // Unable to locate the referenced type "workHere.image.media" in schema
  hotspot?: SanityImageHotspot;
  crop?: SanityImageCrop;
  alt: string;
  _type: "image";
};

export type ServiceReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "service";
};

export type Vacancies = {
  _id: string;
  _type: "vacancies";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  description: string;
  location: string;
  date?: string;
  href: string;
  services?: Array<
    {
      _key: string;
    } & ServiceReference
  >;
};

export type SanityFileAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.fileAsset";
};

export type PageReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "page";
};

export type Page = {
  _id: string;
  _type: "page";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  heroImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: "image";
  };
  content: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?: "normal" | "h2";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt?: string;
        caption?: string;
        variant: "center" | "right";
        _type: "image";
        _key: string;
      }
    | {
        first: ImageTwoFirst;
        second: ImageTwoSecond;
        _type: "imageTwo";
        _key: string;
      }
    | {
        first: First;
        second: Second;
        third: Third;
        fourth: Fourth;
        _type: "imageGallery";
        _key: string;
      }
    | {
        asset?: SanityFileAssetReference;
        media?: unknown;
        title: string;
        _type: "file";
        _key: string;
      }
    | {
        page?: PageReference;
        text?: string;
        _type: "internal-link";
        _key: string;
      }
    | {
        url?: string;
        text?: string;
        _type: "external-link";
        _key: string;
      }
  >;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top: number;
  bottom: number;
  left: number;
  right: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x: number;
  y: number;
  height: number;
  width: number;
};

export type Slug = {
  _type: "slug";
  current: string;
  source?: string;
};

export type StaffReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "staff";
};

export type Blog = {
  _id: string;
  _type: "blog";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  description: string;
  author?: StaffReference;
  link: string;
  image: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: "image";
  };
  publishedAt: string;
};

export type Activity = {
  _id: string;
  _type: "activity";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  date: string;
  location: string;
  internal: boolean;
  registrationUrl?: string;
  isRegistrationUrl: boolean;
};

export type CitationReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "citation";
};

export type Work = {
  _id: string;
  _type: "work";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  order: number;
  description: string;
  startDate?: string;
  endDate?: string;
  services: Array<
    {
      _key: string;
    } & ServiceReference
  >;
  image: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: "image";
  };
  content: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?: "normal" | "blockquote" | "h2";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "data";
        _key: string;
      }
    | {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt?: string;
        caption?: string;
        variant: "center" | "right";
        _type: "image";
        _key: string;
      }
    | {
        first: ImageTwoFirst;
        second: ImageTwoSecond;
        _type: "imageTwo";
        _key: string;
      }
    | {
        first: First;
        second: Second;
        third: Third;
        fourth: Fourth;
        _type: "imageGallery";
        _key: string;
      }
    | {
        first: ImagesThreeFirst;
        second: ImagesThreeSecond;
        third: ImagesThreeThird;
        _type: "imagesThree";
        _key: string;
      }
    | {
        items: Array<string>;
        _type: "tags-list";
        _key: string;
      }
    | {
        title: string;
        items: Array<string>;
        _type: "list-group";
        _key: string;
      }
    | ({
        _key: string;
      } & CitationReference)
  >;
  technologiesTitle: string;
  technologies?: Array<string>;
  stats?: {
    title: string;
    items?: Array<{
      label: string;
      value: string;
      _type: "statItem";
      _key: string;
    }>;
  };
  citation?: CitationReference;
  contactTwo?: {
    label: string;
    title: string;
    contacts: Array<
      {
        _key: string;
      } & StaffReference
    >;
  };
};

export type Logo = {
  _id: string;
  _type: "logo";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  image: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: "image";
  };
  order: number;
};

export type News = {
  _id: string;
  _type: "news";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  description: string;
  slug: Slug;
  author?: StaffReference;
  publishedAt: string;
  tags?: Array<string>;
  content: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?: "normal" | "blockquote" | "h2";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "data";
        _key: string;
      }
    | {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt?: string;
        caption?: string;
        variant: "center" | "right";
        _type: "image";
        _key: string;
      }
    | {
        first: ImageTwoFirst;
        second: ImageTwoSecond;
        _type: "imageTwo";
        _key: string;
      }
    | {
        first: First;
        second: Second;
        third: Third;
        fourth: Fourth;
        _type: "imageGallery";
        _key: string;
      }
    | {
        first: ImagesThreeFirst;
        second: ImagesThreeSecond;
        third: ImagesThreeThird;
        _type: "imagesThree";
        _key: string;
      }
    | {
        items: Array<string>;
        _type: "tags-list";
        _key: string;
      }
    | {
        title: string;
        items: Array<string>;
        _type: "list-group";
        _key: string;
      }
    | ({
        _key: string;
      } & CitationReference)
  >;
};

export type LocationReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "location";
};

export type Staff = {
  _id: string;
  _type: "staff";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
  slug: Slug;
  position: string;
  location: LocationReference;
  serviceType: ServiceReference;
  email?: string;
  image: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  imageSecondary?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type Location = {
  _id: string;
  _type: "location";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
  slug: Slug;
  order: number;
  address: string;
  address2: string;
  phone: string;
  email: string;
  mapLink: string;
  image: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: "image";
  };
};

export type AboutPageType = {
  _id: string;
  _type: "aboutPageType";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  contentTitle: string;
  content: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?: "normal" | "blockquote" | "h2";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "data";
        _key: string;
      }
    | {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt?: string;
        caption?: string;
        variant: "center" | "right";
        _type: "image";
        _key: string;
      }
    | {
        first: ImageTwoFirst;
        second: ImageTwoSecond;
        _type: "imageTwo";
        _key: string;
      }
    | {
        first: First;
        second: Second;
        third: Third;
        fourth: Fourth;
        _type: "imageGallery";
        _key: string;
      }
    | {
        first: ImagesThreeFirst;
        second: ImagesThreeSecond;
        third: ImagesThreeThird;
        _type: "imagesThree";
        _key: string;
      }
    | {
        items: Array<string>;
        _type: "tags-list";
        _key: string;
      }
    | {
        title: string;
        items: Array<string>;
        _type: "list-group";
        _key: string;
      }
    | ({
        _key: string;
      } & CitationReference)
  >;
  summaryLabel: string;
  summaryTitle: string;
  imageGallery?: ImageGallery;
  workHere?: WorkHere;
};

export type WorkherePageType = {
  _id: string;
  _type: "workherePageType";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  heroImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  topLabel: string;
  introText: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?: "normal" | "blockquote" | "h2";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "data";
        _key: string;
      }
    | {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt?: string;
        caption?: string;
        variant: "center" | "right";
        _type: "image";
        _key: string;
      }
    | {
        first: ImageTwoFirst;
        second: ImageTwoSecond;
        _type: "imageTwo";
        _key: string;
      }
    | {
        first: First;
        second: Second;
        third: Third;
        fourth: Fourth;
        _type: "imageGallery";
        _key: string;
      }
    | {
        first: ImagesThreeFirst;
        second: ImagesThreeSecond;
        third: ImagesThreeThird;
        _type: "imagesThree";
        _key: string;
      }
    | {
        items: Array<string>;
        _type: "tags-list";
        _key: string;
      }
    | {
        title: string;
        items: Array<string>;
        _type: "list-group";
        _key: string;
      }
    | ({
        _key: string;
      } & CitationReference)
  >;
  citation?: CitationReference;
  vacanciesTitle: string;
  contentTitel?: string;
  content: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?: "normal" | "blockquote" | "h2";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "data";
        _key: string;
      }
    | {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt?: string;
        caption?: string;
        variant: "center" | "right";
        _type: "image";
        _key: string;
      }
    | {
        first: ImageTwoFirst;
        second: ImageTwoSecond;
        _type: "imageTwo";
        _key: string;
      }
    | {
        first: First;
        second: Second;
        third: Third;
        fourth: Fourth;
        _type: "imageGallery";
        _key: string;
      }
    | {
        first: ImagesThreeFirst;
        second: ImagesThreeSecond;
        third: ImagesThreeThird;
        _type: "imagesThree";
        _key: string;
      }
    | {
        items: Array<string>;
        _type: "tags-list";
        _key: string;
      }
    | {
        title: string;
        items: Array<string>;
        _type: "list-group";
        _key: string;
      }
    | ({
        _key: string;
      } & CitationReference)
  >;
  contactTwo?: {
    label: string;
    title: string;
    text: string;
    contacts: Array<{
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      name?: string;
      position?: string;
      email?: string;
      phone?: string;
      _type: "contact";
      _key: string;
    }>;
  };
  faqTitle: string;
  faqLabel: string;
  faqList?: Array<{
    title: string;
    description: string;
    _key: string;
  }>;
  tldrTitle: string;
  tldrText: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?: "normal" | "blockquote" | "h2";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "data";
        _key: string;
      }
    | {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt?: string;
        caption?: string;
        variant: "center" | "right";
        _type: "image";
        _key: string;
      }
    | {
        first: ImageTwoFirst;
        second: ImageTwoSecond;
        _type: "imageTwo";
        _key: string;
      }
    | {
        first: First;
        second: Second;
        third: Third;
        fourth: Fourth;
        _type: "imageGallery";
        _key: string;
      }
    | {
        first: ImagesThreeFirst;
        second: ImagesThreeSecond;
        third: ImagesThreeThird;
        _type: "imagesThree";
        _key: string;
      }
    | {
        items: Array<string>;
        _type: "tags-list";
        _key: string;
      }
    | {
        title: string;
        items: Array<string>;
        _type: "list-group";
        _key: string;
      }
    | ({
        _key: string;
      } & CitationReference)
  >;
};

export type StaffPageType = {
  _id: string;
  _type: "staffPageType";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  heroImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  galleryText: string;
  imageGallery?: ImageGallery;
  workHere?: WorkHere;
};

export type ServicesPageType = {
  _id: string;
  _type: "servicesPageType";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  heroImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  description: string;
  secondaryImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  citations?: CitationReference;
  contact?: Contact;
};

export type Citation = {
  _id: string;
  _type: "citation";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  text: string;
  service: ServiceReference;
  name: string;
  position: string;
  picture: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type WorkReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "work";
};

export type Service = {
  _id: string;
  _type: "service";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  visible?: boolean;
  order: number;
  title: string;
  slug: Slug;
  description: string;
  heroImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    caption?: string;
    _type: "image";
  };
  content: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?: "normal" | "blockquote" | "h2";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "data";
        _key: string;
      }
    | {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt?: string;
        caption?: string;
        variant: "center" | "right";
        _type: "image";
        _key: string;
      }
    | {
        first: ImageTwoFirst;
        second: ImageTwoSecond;
        _type: "imageTwo";
        _key: string;
      }
    | {
        first: First;
        second: Second;
        third: Third;
        fourth: Fourth;
        _type: "imageGallery";
        _key: string;
      }
    | {
        first: ImagesThreeFirst;
        second: ImagesThreeSecond;
        third: ImagesThreeThird;
        _type: "imagesThree";
        _key: string;
      }
    | {
        items: Array<string>;
        _type: "tags-list";
        _key: string;
      }
    | {
        title: string;
        items: Array<string>;
        _type: "list-group";
        _key: string;
      }
    | ({
        _key: string;
      } & CitationReference)
  >;
  contact?: Contact;
  citation?: CitationReference;
  works?: Array<
    {
      _key: string;
    } & WorkReference
  >;
};

export type WorkerPageType = {
  _id: string;
  _type: "workerPageType";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  heroImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: "image";
  };
  logoTitle: string;
  listTitle: string;
  servicesTitle: string;
  contact?: Contact;
  workCount: number;
};

export type FrontPageType = {
  _id: string;
  _type: "frontPageType";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  topDescription: string;
  heroImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  servicesTitle: string;
  workTitle: string;
  selectedWorks: Array<
    {
      _key: string;
    } & WorkReference
  >;
  activityTitle: string;
  activityImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  vacanciesTitle: string;
  vacanciesImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  vacanciesPoints: Array<{
    title: string;
    description: string;
    _key: string;
  }>;
  contact?: Contact;
};

export type SiteSettings = {
  _id: string;
  _type: "siteSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  description: string;
  analytics: boolean;
  analyticsHostname: string;
  hostname: string;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height: number;
  width: number;
  aspectRatio: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | Contact
  | SanityImageAssetReference
  | ContactImage
  | First
  | Second
  | Third
  | Fourth
  | ImageTwoFirst
  | ImageTwoSecond
  | ImagesThreeFirst
  | ImagesThreeSecond
  | ImagesThreeThird
  | ImageGallery
  | WorkHere
  | WorkHereImage
  | ServiceReference
  | Vacancies
  | SanityFileAssetReference
  | PageReference
  | Page
  | SanityImageCrop
  | SanityImageHotspot
  | Slug
  | StaffReference
  | Blog
  | Activity
  | CitationReference
  | Work
  | Logo
  | News
  | LocationReference
  | Staff
  | Location
  | AboutPageType
  | WorkherePageType
  | StaffPageType
  | ServicesPageType
  | Citation
  | WorkReference
  | Service
  | WorkerPageType
  | FrontPageType
  | SiteSettings
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;
